services:

  rmi-registry:
    build: .
    container_name: rmi-registry
    command: java common.RemoteRegistryServer
    ports:
      - "1099:1099"
    networks:
      - citysync-network

  weather:
    build: .
    container_name: weather-server
    command: java -Djava.rmi.server.hostname=weather weather.WeatherServer
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
    networks:
      - citysync-network

  hospital:
    build: .
    container_name: hospital-server
    command: java -Djava.rmi.server.hostname=hospital hospital.HospitalServer
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
    networks:
      - citysync-network

  traffic:
    build: .
    container_name: traffic-server
    command: java -Djava.rmi.server.hostname=traffic traffic.TrafficServer
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
    networks:
      - citysync-network

  emergency1:
    build: .
    container_name: emergency-server-1
    command: java -Djava.rmi.server.hostname=emergency1 emergency.EmergencyServer EmergencyServer1
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
      - weather
      - hospital
      - traffic
    networks:
      - citysync-network

  emergency2:
    build: .
    container_name: emergency-server-2
    command: java -Djava.rmi.server.hostname=emergency2 emergency.EmergencyServer EmergencyServer2
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
      - weather
      - hospital
      - traffic
    networks:
      - citysync-network

  emergency3:
    build: .
    container_name: emergency-server-3
    command: java -Djava.rmi.server.hostname=emergency3 emergency.EmergencyServer EmergencyServer3
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
      - weather
      - hospital
      - traffic
    networks:
      - citysync-network

  loadbalancer:
    build: .
    container_name: citysync-load-balancer
    command: java -Djava.rmi.server.hostname=loadbalancer loadbalancer.LoadBalancerServer
    environment:
      - RMI_REGISTRY_HOST=rmi-registry
    depends_on:
      - rmi-registry
      - emergency1
      - emergency2
      - emergency3
    networks:
      - citysync-network

networks:
  citysync-network:
    driver: bridge